<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>row_table_employee</name>
   <tag></tag>
   <elementGuidId>45ea0dbd-9a8f-4f76-8a40-f899df8577f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[3]/div[2]/div/div/div[2]/div/div/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td[title=&quot;Friska Borges&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ce6d78dd-e92d-4d8f-b647-02e2f37a98a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Friska Borges</value>
      <webElementGuid>e82912ad-5e4b-4ee6-9724-67c943027d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Friska Borges</value>
      <webElementGuid>e949dcf2-f4ad-4a75-82eb-ebd123866507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employees123&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]</value>
      <webElementGuid>5cc530d3-3842-4eef-9cbc-8602128959cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='employees123']/tbody/tr/td</value>
      <webElementGuid>75cbac71-016f-41ba-9358-f5a93116e576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[1]</value>
      <webElementGuid>1350479a-9706-45a0-9361-f867de86f709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Type'])[1]/following::td[1]</value>
      <webElementGuid>5f4e0c9a-e997-44f9-a068-95489ed7426f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fris@email.com'])[1]/preceding::td[2]</value>
      <webElementGuid>5df8f83f-30ee-4ae9-8295-ef5bb496eed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMPLOYEE'])[1]/preceding::td[4]</value>
      <webElementGuid>45539b77-8534-45f6-8c66-78e00fb21d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Friska Borges']/parent::*</value>
      <webElementGuid>e89a6648-9954-4090-a966-269a1d94cf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>3dabc673-992b-4101-ba71-586f6509af78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Friska Borges' and (text() = 'Friska Borges' or . = 'Friska Borges')]</value>
      <webElementGuid>95baec38-6e28-462a-a901-ab24c0f7383b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
