<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_email</name>
   <tag></tag>
   <elementGuidId>b668cb95-1100-4644-b9ce-27810cd6c9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='employees123']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e17b2d06-bbef-447c-b440-c562437144e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>colin@mail.com</value>
      <webElementGuid>7ec9fdf9-d231-47ea-ac17-4661d661d0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employees123&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]</value>
      <webElementGuid>2405e20a-3500-4804-bbf6-f373f48f7d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='employees123']/tbody/tr/td[3]</value>
      <webElementGuid>59a6907d-13fa-4856-8544-d85715fec832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colin Smith'])[1]/following::td[2]</value>
      <webElementGuid>14cf0cdb-3915-4b64-a42b-5b72d2b26dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[3]</value>
      <webElementGuid>fb691d55-a9bd-465f-96ea-5b810c83bdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMPLOYEE'])[1]/preceding::td[2]</value>
      <webElementGuid>580901de-2913-4e9c-8031-c6bc5c535566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emily Denn'])[1]/preceding::td[4]</value>
      <webElementGuid>bf4cff56-a063-4ee1-ae38-f6aab0e65057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='colin@mail.com']/parent::*</value>
      <webElementGuid>f4019408-ee7f-4664-85b5-a0d9faf6ed72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>18f2ce11-4f4c-4fb2-9675-e7ccb3a5159c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'colin@mail.com' or . = 'colin@mail.com')]</value>
      <webElementGuid>ff3a88ab-2896-487a-9a91-aa27af02fd24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
