<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msreadoutspan_Service</name>
   <tag></tag>
   <elementGuidId>40ab3141-b052-4077-bcd8-7823a0f2937d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>msreadoutspan.msreadout-word-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top']/div/h1/msreadoutspan/msreadoutspan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>msreadoutspan</value>
      <webElementGuid>ae8f64f0-c507-4a72-acc7-cc9ab4c8412a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msreadout-word-highlight</value>
      <webElementGuid>97394276-589f-4142-b1e2-51265011d115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Service</value>
      <webElementGuid>54318f21-cea0-4880-8d44-af98b50cc2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;text-vertical-center&quot;]/h1[1]/msreadoutspan[@class=&quot;msreadout-line-highlight&quot;]/msreadoutspan[@class=&quot;msreadout-word-highlight&quot;]</value>
      <webElementGuid>3babd197-a6dc-431e-9ca9-05b976bd39c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top']/div/h1/msreadoutspan/msreadoutspan</value>
      <webElementGuid>dd2c4162-ceb4-43c8-826b-a306b1086377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::msreadoutspan[2]</value>
      <webElementGuid>f42c3d46-0efb-42d8-92c7-a588eaf5ea31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We Care About Your Health'])[1]/preceding::msreadoutspan[1]</value>
      <webElementGuid>12c38fc4-d84f-4923-a1d2-f6176b0a0661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Appointment'])[1]/preceding::msreadoutspan[1]</value>
      <webElementGuid>773900fe-75be-4f1a-8562-9dab3c52c608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Service']/parent::*</value>
      <webElementGuid>308912a5-3cf0-456a-b44f-dd53af634fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//msreadoutspan/msreadoutspan</value>
      <webElementGuid>a3a0aac5-f46d-46e4-8c18-17b295908b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//msreadoutspan[(text() = 'Service' or . = 'Service')]</value>
      <webElementGuid>28185b0a-d74b-4c4d-9a23-9d312e10b0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
