<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Experience Modal</name>
   <tag></tag>
   <elementGuidId>1efeddc3-2f3c-41c7-8919-7a2240263aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h4[@id='exampleModalLabel1'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>46d41de9-e9a6-4d29-b7b8-84eb909a7699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>3fbe2d75-276a-4823-ab2a-a4721283a324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleModalLabel1</value>
      <webElementGuid>9e2e6ff2-f0ed-44ea-ae2a-2c231b49d1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Experience Modal</value>
      <webElementGuid>07061f2d-041c-4bf6-bd86-05e54b842c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@id=&quot;exampleModalLabel1&quot;]</value>
      <webElementGuid>35ec854d-1c44-4b9b-a7e0-4d65ef0c74e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//h4[@id='exampleModalLabel1'])[2]</value>
      <webElementGuid>bbf81e15-6bac-46ec-81a8-29426dec9a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ExpModal']/div/div/div/h4</value>
      <webElementGuid>8c4d3177-e099-44f5-898b-3ceb6651413d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/following::h4[1]</value>
      <webElementGuid>a012c385-f54b-4f9c-9426-dd98ed8386e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::h4[1]</value>
      <webElementGuid>c470363a-39a6-49d0-9909-41c93eb39363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[2]/preceding::h4[1]</value>
      <webElementGuid>63489b37-0a8d-40be-99fe-8ec5df462caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[3]/preceding::h4[1]</value>
      <webElementGuid>84da078a-a792-4518-8809-8aa1bf5a5b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Experience Modal']/parent::*</value>
      <webElementGuid>0b0939ed-b8ad-4c7f-964f-3d7d9f87a6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/h4</value>
      <webElementGuid>e75244b1-58b2-4f24-9716-78ac3a6fd164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'exampleModalLabel1' and (text() = 'Experience Modal' or . = 'Experience Modal')]</value>
      <webElementGuid>b65093d6-a995-48e4-935f-dc717f465580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
