<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Story Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a36326f1-127d-4feb-9244-ee285e28aec4</testSuiteGuid>
   <testCaseLink>
      <guid>1f20c295-766a-4638-a8ab-949577fff39c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC-Login-Success-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5ed8b53-2dfd-4588-a1db-b80483594e81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aab6ab1-4e2a-42a2-806a-41ccf8b1458d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f63461fc-98a0-49d5-a026-24febc13fd81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC-Login-Locked-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa0d5241-3cb2-4407-9dad-192592b54f6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b0c88c2-9b98-4f99-aafe-25bf475213c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a5d1fa9-07a2-4ccb-a358-4acb0541f3ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b1089e7-fb4a-44bc-958d-ff5b672badf0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC-Login-Failed-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6673c5ae-9fca-4da8-b7c8-37671ff1a400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ebf3082-0dcb-48aa-a0aa-9062e17ccb65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a36c3484-0df4-422f-a70d-0c4ed3dfe591</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC-Login-Failed-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e247698d-4b6d-44a4-a25d-e9e3a3a5c4c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb119369-b5c4-481a-ae7c-f8263a29d458</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>424f24d2-b188-4a2f-9014-0249522f38af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC-Login-Failed-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24fb0f30-e30a-48d9-be8d-8afe71dafab2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ff9d5ea-2787-414a-b35f-9833b87ed6e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC-Login-Failed-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
