<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last_Name_2</name>
   <tag></tag>
   <elementGuidId>3fa8dbf7-b91d-4f5c-ac03-981b011eb497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.header.headerSortDown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table2']/thead/tr/th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>bf53cb94-936a-482a-a88a-97ac6c6051b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header headerSortDown</value>
      <webElementGuid>f42cfaf4-a80b-40f4-9444-daf8182ca025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>47067855-3679-4ff2-8d7b-959358755b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table2&quot;)/thead[1]/tr[1]/th[@class=&quot;header headerSortDown&quot;]</value>
      <webElementGuid>d72ee61d-f7ff-4320-92b7-c923e7f7ac9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table2']/thead/tr/th</value>
      <webElementGuid>4a4c2c72-1866-4cd6-b9f2-c390d9bae0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example 2'])[1]/following::th[1]</value>
      <webElementGuid>1f7d673f-90a2-41d5-804c-77d48215bf60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='delete'])[4]/following::th[1]</value>
      <webElementGuid>2690bd60-a8ce-4c9e-b4e8-27a6560a677b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::th[1]</value>
      <webElementGuid>6d4df8b3-5659-4b2b-9687-128e7196085d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/thead/tr/th</value>
      <webElementGuid>c7d43ef7-4d8f-4888-90be-6000493078b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Last Name' or . = 'Last Name')]</value>
      <webElementGuid>fe750d86-c1f0-45bb-bec4-0bf2c70aaa50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
