<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_This field is required</name>
   <tag></tag>
   <elementGuidId>863e4459-4e7e-4188-a2b9-0106ff3c5b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='experiencemodal']/div/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2f26fc1d-ef64-43a1-8a74-dd1301a3dbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>50388d90-03cc-4980-b2d4-8afd78147b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c655cecf-5e44-4433-89e9-0da46757674a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>0060bc97-b420-4dee-9982-28826210a897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>8049d7c7-ccab-4b72-8a5e-69e1515d8768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experiencemodal&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;error&quot;]</value>
      <webElementGuid>a8a775d8-6e7a-44be-92e3-8d65774bf4c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='experiencemodal']/div/div/label[2]</value>
      <webElementGuid>d46ecdd3-9466-4d02-ae2d-7e550fe411b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[2]/following::label[1]</value>
      <webElementGuid>7aec1316-9213-49a5-89e4-519f3ca4ef45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experience Modal'])[1]/following::label[2]</value>
      <webElementGuid>2b1efb3b-001b-48ba-9871-33b924dbdc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[3]/preceding::label[1]</value>
      <webElementGuid>1704817f-2237-4da4-92d1-453556264348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[5]/preceding::label[2]</value>
      <webElementGuid>284c8053-e7cd-4a36-8f01-aa81e3b01a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This field is required.']/parent::*</value>
      <webElementGuid>ce0d1970-c8f4-4cf4-851e-cc8ac2292633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>83b42106-4e4d-4e68-aa37-58d6eb5555eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'This field is required.' or . = 'This field is required.')]</value>
      <webElementGuid>fe234e09-c500-45dd-8551-f4710ec0901f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
