<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CSV</name>
   <tag></tag>
   <elementGuidId>d9719813-71c8-4560-8ff5-f2f4cc5a404c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dt-button.buttons-csv.buttons-html5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employees123_wrapper']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0faac06e-d145-40ff-98d2-696e7b3cdd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-button buttons-csv buttons-html5</value>
      <webElementGuid>7abb3eb6-48a3-445f-90e7-79e90c6adddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>27c009dc-c877-42cd-9524-8295db19bdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>employees123</value>
      <webElementGuid>a5bf37a4-7746-41e9-b76b-9c6d9c042fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>70aaa3b5-3123-41c5-892f-686cc0ae3b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CSV</value>
      <webElementGuid>8e02f9f4-f5bc-4304-b706-edccb915b71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employees123_wrapper&quot;)/div[@class=&quot;dt-buttons&quot;]/a[@class=&quot;dt-button buttons-csv buttons-html5&quot;]</value>
      <webElementGuid>cd6bf6a3-8fa7-4c12-b0a2-154a0c77af46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employees123_wrapper']/div/a[2]</value>
      <webElementGuid>d2f64134-bdd6-433c-9e85-d7126a5428e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/following::a[1]</value>
      <webElementGuid>2f93827d-b992-4c83-ae10-6f9341813ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/following::a[2]</value>
      <webElementGuid>c860de25-75ff-4455-8111-fbd585a4724f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>b63a33b5-19eb-4474-b4a5-2a49105981ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>d1a827ce-1f9d-4d8f-a64d-0993e58050d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a[2]</value>
      <webElementGuid>9799faee-2b66-4c5f-9049-1b64a81bddd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'CSV' or . = 'CSV')]</value>
      <webElementGuid>85fa411a-ef12-472c-af5c-ae8f7636c9ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
