<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_designation</name>
   <tag></tag>
   <elementGuidId>beb25c71-b3f3-4ee0-998b-0d6d0e16e6ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main-wrapper&quot;]/div[2]/div[3]/div[2]/div/div/div[2]/form/div[5]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
